### ISSUE TITLE
请问k8s如何和spring cloud gateway整合?

### ISSUE THREAD

**Issue by jtarea** [zq2599/blog_demos#2]
routes中的uri应该如何和k8s里面的pod对应起来？

**Comment by zq2599** [comment]
您好，借助spring-cloud-kubernetes框架，spring cloud gateway在kubernetes环境可以继续扮演网关的角色，将请求路由到kubernetes的service，并且过滤、限流、鉴权等功能都能继续使用，routes中的url和k8s中的service对应，如果您想了解更多，或者实战体验spring cloud gateway与k8s service的路由，请参考我的最新文章《spring-cloud-kubernetes与SpringCloud Gateway》，地址是：https://blog.csdn.net/boling_cavalry/article/details/95001691

**Comment by jtarea** [comment]
感谢您的答复！我会继续关注您的spring cloud相关教程。
