### ISSUE TITLE
代码该更新一下啦~~

### ISSUE THREAD

**Issue by mmaotai** [zq2599/blog_demos#38]
升级下版本  跑了下zk, 竟然还是sb1.3

**Comment by zq2599** [comment]
> 升级下版本 跑了下zk, 竟然还是sb1.3

实在不好意思，这个仓库里东西太多太杂，您说的具体是哪个目录下的资源，或者说对应的是哪篇文章？我好去修改

**Comment by zq2599** [comment]
您好，能否指出是哪个项目的版本太低？我更新代码的时候也顺便把文章中的相关部分也更新掉，我的邮箱zq2599@gmail.com，谢谢
